version: '3.2'
services:
  concourse-db:
    image: postgres:9.5
    volumes: ['./database:/database']
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    command: web
    ports: ["8080:8080"]
    volumes: ["./keys:/concourse-keys","/var/run/docker.sock:/var/run/docker.sock"]
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_GARDEN_DNS_SERVER: ${CONCOURSE_GARDEN_DNS_SERVER}
      CONCOURSE_EXTERNAL_URL: "localhost:5656"
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
    dns: ${CONCOURSE_GARDEN_DNS_SERVER}

  concourse-worker:
    image: concourse/concourse
    privileged: true
    command: worker
    volumes: ["./keys:/concourse-keys","/var/run/docker.sock:/var/run/docker.sock"]
    environment:
      CONCOURSE_GARDEN_DNS_SERVER: ${CONCOURSE_GARDEN_DNS_SERVER}
      CONCOURSE_TSA_HOST: concourse-web
    dns: ${CONCOURSE_GARDEN_DNS_SERVER}

  nexus:
    image: sonatype/nexus
    ports: ["8081:8081"]
    volumes: ["./nexus-data:/sonatype-work"]

  deployment:
    image: hylke1982/run-on-docker
    ports: ["8000:8000"]
    privileged: true
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ${CONCOURSE_GARDEN_DNS_SERVER}
    dns: ${CONCOURSE_GARDEN_DNS_SERVER}

networks:
  default:
    external:
      name: servicediscovery_default
