# Resource section
resources:
- name: sources # Name of the resource
  type: git # Resource type
  source:
    uri: git@github.com:mdonkers/DevOpsTraining.git
    branch: master
    private_key: ((private-repo-key))
- name: put-sources # Name of the resource
  type: git # Resource type
  source:
    uri: git@github.com:mdonkers/DevOpsTraining.git
    branch: master
    private_key: ((private-repo-key))

# Jobs section
jobs:
- name: build
  plan:
  - get: sources
    trigger: true
  - task: build software
    file: sources/CI/task-build.yml
- name: test # Name of the job
  plan:
  - get: sources # Download the sources
    trigger: true
    passed: [build] # Trigger after job build has passed
  - task: unit test
    file: sources/CI/task-unit-test.yml
- name: deploy # Name of the job
  plan:
  - get: sources # Download the sources
    trigger: true
    passed: [test] # Trigger after job test has passed
  - task: tag, publish and publish new version
    file: sources/CI/task-deploy.yml
  - put: put-sources
    params: {repository: sources-output} # Push latest version after tagging en version bump
- name: run
  plan:
  - get: sources # Download the sources
    trigger: true
    passed: [deploy] # Trigger after job test has passed
  - task: run the application in the blue environment
    file: sources/CI/task-run.yml
