version: "2"
services:
  consul:
    image: "progrium/consul:latest"
    container_name: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: "-server -bootstrap -ui-dir /ui"

  registrator:
    image: "gliderlabs/registrator"
    volumes: ["/var/run/docker.sock:/tmp/docker.sock"]
    command: "consul://consul:8500"
    depends_on:
    - consul

  proxy:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "23240:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml